{"message":"Unable to ensure uniqueness for usernames: ","stack":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","name":"MongoNetworkError","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-02-06T07:20:08.532Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","stack":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","name":"MongoNetworkError","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-02-06T07:20:08.537Z"}
{"message":"Unable to ensure uniqueness for role name: ","stack":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","name":"MongoNetworkError","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-02-06T07:20:08.537Z"}
{"message":"Unable to ensure uniqueness for usernames: ","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","name":"MongoNetworkError","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-02-06T07:20:54.311Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","name":"MongoNetworkError","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-02-06T07:20:54.316Z"}
{"message":"Unable to ensure uniqueness for role name: ","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","name":"MongoNetworkError","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-02-06T07:20:54.317Z"}
{"message":"Unable to ensure uniqueness for usernames: ","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","name":"MongoNetworkError","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-02-06T07:22:56.300Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","name":"MongoNetworkError","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-02-06T07:22:56.305Z"}
{"message":"Unable to ensure uniqueness for role name: ","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","name":"MongoNetworkError","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-02-06T07:22:56.306Z"}
{"message":"Unable to ensure uniqueness for usernames: ","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","name":"MongoNetworkError","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-02-06T07:25:59.446Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","name":"MongoNetworkError","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-02-06T07:25:59.450Z"}
{"message":"Unable to ensure uniqueness for role name: ","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","name":"MongoNetworkError","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-02-06T07:25:59.451Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:26:45.945Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:26:45.950Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:26:47.989Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:26:47.992Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:26:48.003Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:26:50.035Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:26:50.037Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:26:50.051Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:26:52.087Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:26:52.089Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:26:52.103Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:26:55.050Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:26:55.052Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:26:55.066Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:26:58.873Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:29:12.715Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:29:14.841Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:29:16.972Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:29:19.794Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:29:23.450Z"}
{"message":"Unable to ensure uniqueness for usernames: ","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","name":"MongoNetworkError","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-02-06T08:52:18.189Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","name":"MongoNetworkError","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-02-06T08:52:18.194Z"}
{"message":"Unable to ensure uniqueness for role name: ","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","name":"MongoNetworkError","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-02-06T08:52:18.195Z"}
{"message":"Unable to ensure uniqueness for usernames: ","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","name":"MongoNetworkError","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-02-06T11:49:41.906Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","name":"MongoNetworkError","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-02-06T11:49:41.911Z"}
{"message":"Unable to ensure uniqueness for role name: ","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","name":"MongoNetworkError","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-02-06T11:49:41.911Z"}
{"message":"Unable to ensure uniqueness for usernames: ","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","name":"MongoNetworkError","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-02-06T13:22:50.411Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","name":"MongoNetworkError","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-02-06T13:22:50.416Z"}
{"message":"Unable to ensure uniqueness for role name: ","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","name":"MongoNetworkError","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-02-06T13:22:50.417Z"}
{"message":"Unable to ensure uniqueness for usernames: ","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","name":"MongoNetworkError","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-02-06T14:11:10.930Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","name":"MongoNetworkError","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-02-06T14:11:10.933Z"}
{"message":"Unable to ensure uniqueness for role name: ","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","name":"MongoNetworkError","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-02-06T14:11:10.933Z"}
